#cloud-config
packages:
  - yum
runcmd:
  - 'yum update' 
  - 'sed -i "s/#MaxSessions 10/MaxSessions 50/" /etc/ssh/sshd_config'
  - 'sed -i "s/X11Forwarding yes/X11Forwarding no/" /etc/ssh/sshd_config'
  - 'sed -i "s/PermitRootLogin yes/PermitRootLogin prohibit-password/" /etc/ssh/sshd_config'
  - 'sed -i "s/#AllowAgentForwarding yes/AllowAgentForwarding no/" /etc/ssh/sshd_config'
  - 'echo "MaxStartups 50:30:80"  >> /etc/ssh/sshd_config'
  - 'echo "AllowStreamLocalForwarding no"  >> /etc/ssh/sshd_config'
  - 'service ssh restart'